version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "23:30"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: easy-peasy
    versions:
    - ">= 4.a, < 5"
  - dependency-name: next-pwa
    versions:
    - 5.0.2
    - 5.0.4
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.11.1
    - 4.14.2
  - dependency-name: next
    versions:
    - 10.0.4
    - 10.0.6
  - dependency-name: react-multi-select-component
    versions:
    - 3.0.8
    - 3.1.2
  - dependency-name: dayjs
    versions:
    - 1.9.8
  - dependency-name: typescript
    versions:
    - 4.1.3
  - dependency-name: react-leaflet
    versions:
    - 3.0.5
  - dependency-name: yup
    versions:
    - 0.32.8
