# Read more at https://dependabot.com/#how-it-works
version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "weekly"
    default_reviewers:
      - "harshzalavadiya"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "semver:patch"
